language: elixir
matrix:
  include:
    - otp_release: 22.1
      elixir: 1.10
env:
  global:
    - MIX_HOME=$HOME/.mix
script:
  - MIX_ENV=test mix compile --force --warnings-as-errors
  - mix docs
  - mix test
  - mix format --check-formatted
  - mix dialyzer
cache:
  directories:
  - $HOME/.mix
  - deps
  - _build
  - demos/priv_check_example/deps
